### ISSUE TITLE
unittests are not run

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#104]
Take this sample code from https://docs.python.org/3/library/unittest.html
```python
import unittest

class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        self.assertEqual('foo'.upper(), 'FOO')

    def test_isupper(self):
        self.assertTrue('FOO'.isupper())
        self.assertFalse('Foo'.isupper())

    def test_split(self):
        s = 'hello world'
        self.assertEqual(s.split(), ['hello', 'world'])
        # check that s.split fails when the separator is not a string
        with self.assertRaises(TypeError):
            s.split(2)

if __name__ == '__main__':
    unittest.main()
```

AREPL says:

> Ran 0 tests in 0.000s

Expected result: it runs 3 tests

**Comment by Almenon** [comment]
I wasn't able to easily find out the reason behind this so moving to next milestone.

**Comment by Almenon** [comment]
From my preliminary investigation looks like it's related to __import__('__main__') resulting in different output in arepl / vs interpreter

**Comment by Almenon** [comment]
Still an issue, although different error message now:

```
Traceback (most recent call last):
  line 20, in <module>
  File "C:\Python312\Lib\unittest\main.py", line 105, in __init__
    self.runTests()
  File "C:\Python312\Lib\unittest\main.py", line 284, in runTests
    sys.exit(_NO_TESTS_EXITCODE)
[SystemExit: 5](https://www.google.com/search?q=python%20SystemExit:%205)
```

https://github.com/python/cpython/blob/main/Lib/unittest/main.py#L273

Same issue if I just pass the code directly into a simple exec:

```
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('testunittest.py') as f:
...   code = f.read()
...

>>> locals = {}
>>> exec(code, locals)
----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN
```
