### ISSUE TITLE
hypothesis fails when testing sucessful test

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#113]
I was following the guide on https://hypothesis.readthedocs.io/en/master/quickstart.html and hypothesis sucessfully ran when the function being tested resulted in a error but when I tried the function that worked correctly hypothesis broke:

```python
def encode(input_string):
    if not input_string: return [] # this line makes function work correctly
    count = 1
    prev = ''
    lst = []
    for character in input_string:
        if character != prev:
            if prev:
                entry = (prev, count)
                lst.append(entry)
            count = 1
            prev = character
        else:
            count += 1
    else:
        entry = (character, count)
        lst.append(entry)
    return lst


def decode(lst):
    q = ''
    for character, count in lst:
        q += character * count
    return q

from hypothesis import given
from hypothesis.strategies import text

@given(text())
def test_decode_inverts_encode(s):
    assert decode(encode(s)) == s

if __name__ == '__main__':
    test_decode_inverts_encode()

```

error:

```Traceback (most recent call last):
  line 35, in <module>
  line 31, in test_decode_inverts_encode
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\core.py", line 837, in wrapped_test
    generator_kwargs, argspec, test, settings
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\core.py", line 352, in process_arguments_to_given
    search_strategy.validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 379, in validate
    self.do_validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\lazy.py", line 130, in do_validate
    w.validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 379, in validate
    self.do_validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\collections.py", line 38, in do_validate
    s.validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 379, in validate
    self.do_validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 553, in do_validate
    self.mapped_strategy.validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 379, in validate
    self.do_validate()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\lazy.py", line 127, in do_validate
    w = self.wrapped_strategy
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\lazy.py", line 113, in wrapped_strategy
    *self.__args, **self.__kwargs
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\strategies.py", line 780, in fixed_dictionaries
    check_strategy(v)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\searchstrategy\strategies.py", line 641, in check_strategy
    check_type(SearchStrategy, arg, name)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\hypothesis\internal\validation.py", line 40, in check_type
    % (typ_string, name, arg, type(arg).__name__))
hypothesis.errors.InvalidArgument: Expected SearchStrategy but got text() (type=LazyStrategy)
```

**Comment by Almenon** [comment]
works fine w/ python 3.12 hypothesis==6.118.7
