### ISSUE TITLE
webview error

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#125]
```
Error: Webview is disposed
	at e.assertNotDisposed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:762:630)
	at e.get [as webview] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:119)
	at PythonPreview.updateContent (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\pythonPreview.js:226:19)
	at caller (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\throttle.js:48:31)
	at PythonPreview.throttledUpdate (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\throttle.js:66:13)
	at PythonPreview.updateError (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\pythonPreview.js:157:18)
	at PreviewContainer.updateError (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\previewContainer.js:81:28)
	at PreviewContainer.handleResult (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\previewContainer.js:45:18)
	at syntaxPromise.then.catch (C:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.2\out\src\toAREPLLogic.js:59:35)
	at <anonymous>
```

**Comment by Almenon** [comment]
This happens because I update the html asynchronusly, so there is a small chance that the user exits the webview and an leftover update gets called afterwards.
