### ISSUE TITLE
PicklingError on the second arepl run when using requests_cache

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#132]
```
Traceback (most recent call last):
  line 19, in <module>
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 126, in request
    **kwargs
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 126, in request
    **kwargs
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 99, in send
    return send_request_and_cache_response()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 99, in send
    return send_request_and_cache_response()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 93, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\backends\base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\backends\storage\dbdict.py", line 160, in __setitem__
    sqlite.Binary(pickle.dumps(item)))
_pickle.PicklingError: Can't pickle <class 'requests_cache.backends.base._Store'>: it's not the same object as requests_cache.backends.base._Store
```

If I add the below line of code at the end to unload the module (so it gets reloaded each run):
```python
del sys.modules['requests_cache']
```
then on the _third_ run I get this error:

```
Traceback (most recent call last):
  line 4, in <module>
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\__init__.py", line 28, in <module>
    from .core import(
  File "C:\Users\almenon\AppData\Roaming\Python\Python36\site-packages\requests_cache\core.py", line 21, in <module>
    ver = tuple(map(int, requests.__version__.split(".")))
AttributeError: module 'requests.__version__' has no attribute 'split'
```

I get the first error - the module state is kept inbetween runs, so subsequent arepl runs will behave differently.  But the second error is very odd.  The module is reloaded each run. And why would it only appear the _third_ time?

**Comment by Almenon** [comment]
This may be fixed with #162. Closing - if anyone runs into same error feel free to comment and I'll reopen.
