### ISSUE TITLE
Sorry, AREPL has ran into an error  OSError: append: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mahipatilin** [Almenon/AREPL-vscode#181]
```
Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/pythonEvaluator.py", line 414, in <module>
    myReturnInfo = exec_input(data.evalCode, data.savedCode, data.filePath)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/pythonEvaluator.py", line 382, in exec_input
    userVariables = pickle_user_vars(evalLocals)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/pythonEvaluator.py", line 267, in pickle_user_vars
    return jsonpickle.encode(userVariables, max_depth=100) # any depth above 245 resuls in error and anything above 100 takes too long to process
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 75, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 181, in flatten
    return self._flatten(obj)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 185, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 206, in _flatten_obj
    return flatten_func(obj)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 463, in _flatten_dict_obj
    flatten(k, v, data)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 538, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 185, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 206, in _flatten_obj
    return flatten_func(obj)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 264, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/pickler.py", line 295, in _flatten_obj_instance
    has_reduce, has_reduce_ex = util.has_reduce(obj)
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/util.py", line 395, in has_reduce
    if not is_reducible(obj) or is_type(obj):
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/util.py", line 350, in is_reducible
    is_list_like(obj) or
  File "/home/cdac/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/jsonpickle/util.py", line 324, in is_list_like
    return hasattr(obj, '__getitem__') and hasattr(obj, 'append')
  File "/home/cdac/Downloads/extract/anaconda3/lib/python3.6/ctypes/__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "/home/cdac/Downloads/extract/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: append: cannot open shared object file: No such file or directory
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Python 3.6.5 :: Anaconda, Inc.

 "Developer: Open Log File...", choose Extension Host
```
[2019-02-13 10:27:55.277] [exthost] [info] extension host started
[2019-02-13 10:27:55.313] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.313] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2019-02-13 10:27:55.319] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.319] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2019-02-13 10:27:55.342] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.342] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2019-02-13 10:27:55.479] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.479] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2019-02-13 10:27:55.487] [exthost] [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.487] [exthost] [info] ExtensionService#loadCommonJSModule /home/cdac/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/extension
[2019-02-13 10:27:55.501] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2019-02-13 10:27:55.501] [exthost] [info] ExtensionService#loadCommonJSModule /home/cdac/.vscode/extensions/dbaeumer.vscode-eslint-1.8.0/client/out/extension
[2019-02-13 10:27:55.584] [exthost] [info] ExtensionService#_doActivateExtension GrapeCity.gc-excelviewer {"startup":false,"activationEvent":"onLanguage:plaintext"}
[2019-02-13 10:27:55.584] [exthost] [info] ExtensionService#loadCommonJSModule /home/cdac/.vscode/extensions/grapecity.gc-excelviewer-2.1.28/out/src/extension
[2019-02-13 10:27:55.983] [exthost] [info] eager extensions activated
[2019-02-13 10:28:04.338] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-02-13 10:28:04.338] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/python/out/pythonMain
[2019-02-13 10:28:04.361] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-02-13 10:28:04.361] [exthost] [info] ExtensionService#loadCommonJSModule /home/cdac/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension
[2019-02-13 10:32:25.750] [exthost] [error] [ms-python.python] provider FAILED
[2019-02-13 10:32:25.754] [exthost] [error] TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/home/cdac/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:96546)
[2019-02-13 10:32:26.921] [exthost] [error] [ms-python.python] provider FAILED
[2019-02-13 10:32:26.921] [exthost] [error] TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/home/cdac/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:96546)
[2019-02-13 10:32:28.505] [exthost] [error] [ms-python.python] provider FAILED
[2019-02-13 10:32:28.505] [exthost] [error] TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/home/cdac/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:96546)
[2019-02-13 10:32:37.539] [exthost] [error] [ms-python.python] provider FAILED
[2019-02-13 10:32:37.540] [exthost] [error] TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/home/cdac/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:96546)
[2019-02-13 10:33:25.028] [exthost] [info] ExtensionService#_doActivateExtension almenon.arepl {"startup":false,"activationEvent":"onCommand:extension.currentAREPLSession"}
[2019-02-13 10:33:25.028] [exthost] [info] ExtensionService#loadCommonJSModule /home/cdac/.vscode/extensions/almenon.arepl-1.0.8/out/src/extension
```

**Comment by Almenon** [comment]
I think I can fix this - what is the python code you used that got this error?

**Comment by mahipatilin** [comment]
I used a scapy program as below:

from scapy.all import *

arp = ARP()
ether = Ether()

arp.pdst = "10.244.0.132"
arp.show()
ether.show()

**Comment by Almenon** [comment]
okay, thanks. While I fix this bug here is a workaround: only import the items you need.  For example, the following program works fine in arepl:

```python
from scapy.all import ARP, Ether

arp = ARP()
ether = Ether()

arp.pdst = "10.244.0.132"
arp.show()
ether.show()

```

Also generally speaking it is good python practice to not import * (although I can understand using it for quick scripting purposes)

**Comment by Almenon** [comment]
Good news and bad news :/

Good news: I fixed it in my local dev environment and I will release a update with the fix.

Bad news: Even with the fix importing * imports so much stuff that arepl can't handle it. It's literally thousands of lines.  You'll have to only import the stuff you need for arepl to work properly.

**Comment by mahipatilin** [comment]
Importing specific modules as below worked.
```python
from scapy.all import ARP, Ether
```
Thanks for that quick fix

**Comment by Almenon** [comment]
I just released a update with changes to the backend - scapy should no longer crash arepl (although like I said before importing * will still be slow)
