### ISSUE TITLE
AREPL not working at all

### ISSUE THREAD

**Issue by al73rna** [Almenon/AREPL-vscode#186]
i keep getting the following error even for a simple print statement.
```
SyntaxError: invalid syntax
  File "/home/****/.vscode/extensions/almenon.arepl-1.0.8/node_modules/arepl-backend/python/pythonEvaluator.py", line 164
    raise StopIteration("There is no more input") from None
                                                     ^
SyntaxError: invalid syntax

```
Python version is 3.6.6

**Comment by al73rna** [comment]
More info:
seems to be working fine after downgrading to the previous version (1.0.7)
The above error only happening in (1.0.8)
VSCode version is 1.31.0

**Comment by Almenon** [comment]
That's very strange because the "from None" syntax is supported even in python 3.5 .....

https://docs.python.org/3.5/library/exceptions.html

and I run unit tests against python 3.5 as well and the unit test passed. If there was a syntax error it would have caught it. https://travis-ci.org/Almenon/AREPL-backend/jobs/491479930

Furthermore "raise StopIteration("There is no more input") from None" is _**also present in version 1.0.7!**_

So it makes 0 sense as to why you get the error in 1.0.8 but not in 1.0.7. 

I suspect something else is going on but I have no clue what.

Do you have any ideas?

**Comment by Almenon** [comment]
Oh I have a guess: one of the changes v1.0.8 introduced is that it uses the python extension's python path. It's possible that your python extension is configured to use python 2 and thus you get that error.  What path do you have configured in the python extension (I'm assuming you have it installed). If it's just "python" that would invoke python2 - can you change it to be "python3" and try 1.0.8 again?

**Comment by Almenon** [comment]
Actually I just confirmed it, that's definitely the case.

https://repl.it/@almenon/TriflingDrabFrontend

AREPL is only compatible with python 3 - python 2 is not supported.

The error message is confusing, sorry. I'll look into giving the user a better one.

**Comment by al73rna** [comment]
Yes, you were right. Can confirm that it's fixed after setting my interpreter to use python 3. Awesome!

**Comment by Almenon** [comment]
I just released a update that has a better error message if you're using python 2 :)

**Comment by talyaniv** [comment]
I have the same issue with Python 3.

Python 3.6.8 (Anaconda)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Mac OSX Mojave 10.14.3

AREPL preview:
`
Print Output:
  File "/Users/talyaniv/.vscode/extensions/almenon.arepl-1.0.9/node_modules/arepl-backend/python/pythonEvaluator.py", line 169
    raise StopIteration("There is no more input") from None
                                                     ^
SyntaxError: invalid syntax
`

exhost.log:
`
[2019-02-21 10:18:57.130] [exthost] [info] extension host started
[2019-02-21 10:18:57.155] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-02-21 10:18:57.155] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2019-02-21 10:18:57.158] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-02-21 10:18:57.159] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/extension
[2019-02-21 10:18:57.162] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-02-21 10:18:57.162] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2019-02-21 10:18:57.186] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-02-21 10:18:57.186] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/extension
[2019-02-21 10:18:57.188] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2019-02-21 10:18:57.188] [exthost] [info] ExtensionService#loadCommonJSModule /Users/talyaniv/.vscode/extensions/dbaeumer.vscode-eslint-1.8.0/client/out/extension
[2019-02-21 10:18:57.225] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-02-21 10:18:57.225] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/python/out/pythonMain
[2019-02-21 10:18:57.226] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-02-21 10:18:57.226] [exthost] [info] ExtensionService#loadCommonJSModule /Users/talyaniv/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension
[2019-02-21 10:18:57.724] [exthost] [info] eager extensions activated
[2019-02-21 10:19:03.931] [exthost] [info] ExtensionService#_doActivateExtension almenon.arepl {"startup":false,"activationEvent":"onCommand:extension.currentAREPLSession"}
[2019-02-21 10:19:03.931] [exthost] [info] ExtensionService#loadCommonJSModule /Users/talyaniv/.vscode/extensions/almenon.arepl-1.0.9/out/src/extension
`

**Comment by Almenon** [comment]
@talyaniv That error only happens with python 2.  You have 3, sure, but arepl will only use the version you have configured in your path.  Check python.pythonpath - what is that pointing too? And what is the value of arepl.pythonpath?

**Comment by talyaniv** [comment]
Thanks @Almenon! Just made sure the VSCode interpreter was set correctly and the issue was fixed. I hope it will help others.

**Comment by Shreya-Gupta02** [comment]
internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at PythonShell.send (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.22\node_modules\python-shell\index.js:285:20)
	at PythonEvaluator.execCode (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.22\node_modules\arepl-backend\index.js:62:22)
	at ToAREPLLogic.onUserInput (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.22\out\src\toAREPLLogic.js:79:34)
	at PreviewManager.onAnyDocChange (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.22\out\src\PreviewManager.js:271:51)
	at listOnTimeout (internal/timers.js:533:17)
	at processTimers (internal/timers.js:475:7)

Print Output:
Variables:


report an issue | ⭐ rate me ⭐ | talk on gitter | Tweet #arepl
