### ISSUE TITLE
TypeError: keys must be a string

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#196]
```python
	
Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 422, in <module>
    myReturnInfo = exec_input(data.evalCode, data.savedCode, data.filePath)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 390, in exec_input
    userVariables = pickle_user_vars(evalLocals)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 274, in pickle_user_vars
    fail_safe=lambda x:"AREPL could not pickle this object"
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 80, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 165, in encode
    raise e
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Anaconda\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Anaconda\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

Not sure why this is happening. 

If anyone could provide the python code that causes this error that would be great.

**Comment by mccannjb** [comment]
I'm experiencing this bug when attempting to create a pandas Series object using a hierarchical index.
```
import pandas as pd
lets = ['A', 'B', 'C']
nums = ['1', '2', '3']
midx = pd.MultiIndex.from_product([lets, nums])
units = pd.Series(0, index=midx)
```
As soon as the `units` assignment is evaluated, AREPL throws an error "keys must be a string". 
I think this might be related to parsing variables for display in AREPL, as the error only occurs when the variable assignment is completed and does not occur when setting with a non-hierarchical index. 

Examples
----------
- Non-hierarchical
`units = pd.Series(0, index=[1,2,3])` produces expected results.
- Hierarchical
`units = pd.Series(0, index=[[1], [2], [3]])` results in the error

**Comment by Almenon** [comment]
Thanks for the code @mccannjb !

This appears to be a error with jsonpickle, the library I use for encoding the variables into json. 

https://github.com/jsonpickle/jsonpickle/issues/287

As a temporary workaround you can comment out line 48 `jsonpickle_pandas.register_handlers()` in `%userprofile%\.vscode\extensions\almenon.arepl-1.0.20\node_modules\arepl-backend\python\pickler.py`

If you're on linux / mac the path will be `$HOME/.vscode/extensions/almenon.arepl-1.0.20/node_modules/arepl-backend/python/pickler.py`

**Comment by davvid** [comment]
Hmm, what's the behavior when using `keys=True` when encoding?  This existing feature that attempts to support non-string dict keys by sending the object through encode() again, but I'm not sure whether this is the same use case.

Thanks for your help on this.  Let me know if `keys=True` helps so we can document it, and so we can write a test to make sure this use case keeps working in the future.

**Comment by davvid** [comment]
Nevermind, keys=True is not involved here.  First, I would suggest trying the latest version, which has better pandas support.  When I tried to add these Series objects to our current test suite, I didn't get any failures.

I then added more assertions that pointed out that we weren't handling MultiIndex series indexes, and have it passing all tests in addition to these new ones that validate that the index values are preserved.

I'm going to tag and release the current master (in case I broke something the tests don't cover, and so that users have more version options for edge cases) and then push up a new commit which should resolve this issue.  The older pandas.Series handler wasn't completely generalized, whereas the new one should be able to handle these just fine, but we'll see.

**Comment by davvid** [comment]
Oops, sorry, I thought I was commenting on jsonpickle's issue tracker.  In any case, what's in master now handles these series objects just fine from the jsonpickle side, so hopefully this'll help out here too.
