### ISSUE TITLE
TypeError: Cannot read property 'setDecorations' of undefined

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#197]
```
TypeError: Cannot read property 'setDecorations' of undefined
	at PreviewContainer.updateErrorGutterIcons (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\out\src\previewContainer.js:94:44)
	at PreviewContainer.handleResult (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\out\src\previewContainer.js:54:22)
	at PythonEvaluator.startAndBindPython.pythonEvaluator.onResult.result [as onResult] (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\out\src\PreviewManager.js:136:35)
	at PythonEvaluator.handleResult (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\index.js:176:22)
	at PythonShell.startPython.pyshell.on.message (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\index.js:117:18)
	at PythonShell.emit (events.js:182:13)
	at C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\python-shell\index.js:308:22
	at Array.forEach (<anonymous>)
	at PythonShell.recieveInternal (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\python-shell\index.js:306:15)
	at PythonShell.receive (C:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\python-shell\index.js:280:21)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:260:13)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by Almenon** [comment]
Just saw this in telemtry not sure why or when it happens exactly

**Comment by Almenon** [comment]
looked into this still not sure why it happens but easy fix.
