### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#200]
> extensionService.ts:800 Activating extension 'almenon.arepl' failed: Command failed: C:\Program Files\Python36\python.exe -m site --user-site

```
	at checkExecSyncError (child_process.js:615:11)
	at Object.execSync (child_process.js:652:13)
	at Object.execSync (ELECTRON_ASAR.js:746:23)
	at getsitePackagePath (C:\Users\caleb\.vscode\extensions\almenon.arepl-1.0.10\out\src\registerAreplDump.js:30:28)
	at Object.registerAreplDump (C:\Users\caleb\.vscode\extensions\almenon.arepl-1.0.10\out\src\registerAreplDump.js:11:29)
	at activate (C:\Users\caleb\.vscode\extensions\almenon.arepl-1.0.10\out\src\extension.js:31:25)
	at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:354)
	at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:25)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:206
```

**Comment by Almenon** [comment]
I just need to wrap it in quotes.

**Comment by Almenon** [comment]
signficance of error: annoying error popup, dump might not work
