### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#22]
```python
Traceback (most recent call last):
  File "C:\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python35\lib\py_compile.py", line 186, in <module>
    sys.exit(main())
  File "C:\Python\Python35\lib\py_compile.py", line 178, in main
    compile(filename, doraise=True)
  File "C:\Python\Python35\lib\py_compile.py", line 143, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 112, in _write_atomic
PermissionError: [WinError 5] Access is denied: 'c:\\dev\\AREPL-vscode\\personal\\__pycache__\\t.cpython-35.pyc.2420628369792' -> 'c:\\dev\\AREPL-vscode\\personal\\__pycache__\\t.cpython-35.pyc'
```

Very easy to reproduce when extension isinstalled: just use below:

```python
import turtle
turtle.forward(100)
```

Happens sometimes when the syntax check happens before restart.

**Comment by Almenon** [comment]
https://stackoverflow.com/questions/154443/how-to-avoid-pyc-files
