### ISSUE TITLE
Running "eval python in real time (current doc)" causes error every time

### ISSUE THREAD

**Issue by awvalenti** [Almenon/AREPL-vscode#239]
This may be caused by running Python 2 instead of 3 (I have both installed). Can I change only AREPL to run Python3 instead of changing for the whole system, which would probably cause problems?

```
Print Output:
  File "/home/andre/.vscode/extensions/almenon.arepl-1.0.13/node_modules/arepl-backend/python/pythonEvaluator.py", line 172
    raise StopIteration("There is no more input") from None
                                                     ^
SyntaxError: invalid syntax
```
![image](https://user-images.githubusercontent.com/834921/56071747-b5d20c80-5d66-11e9-9eaa-a297e6360aab.png)

Python:
python --version: Python 2.7.15rc1
python3 --version: Python 3.6.7

OS:
(Linux Mint Cinnamon 19)
uname --all: Linux w175 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

VSCode:
Versão: Commit de 1.32.3: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 Data: 2019-03-14T23:38:49.842Z elétron: 3.1.6 Chrome: 66.0.3359.181 node. js: 10.2.0 V8: 6.6.346.32 OS: Linux x64 4.15.0-46-generic

```
[2019-04-12 20:56:42.416] [exthost] [info] extension host started
[2019-04-12 20:56:42.457] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-04-12 20:56:42.457] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2019-04-12 20:56:42.464] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-04-12 20:56:42.464] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2019-04-12 20:56:42.469] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-04-12 20:56:42.469] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2019-04-12 20:56:42.488] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-04-12 20:56:42.488] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2019-04-12 20:56:42.490] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-04-12 20:56:42.490] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/python/out/pythonMain
[2019-04-12 20:56:42.490] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-04-12 20:56:42.490] [exthost] [info] ExtensionService#loadCommonJSModule /home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension
[2019-04-12 20:56:42.910] [exthost] [info] eager extensions activated
[2019-04-12 20:57:27.081] [exthost] [info] ExtensionService#_doActivateExtension almenon.arepl {"startup":false,"activationEvent":"onCommand:extension.currentAREPLSession"}
[2019-04-12 20:57:27.081] [exthost] [info] ExtensionService#loadCommonJSModule /home/andre/.vscode/extensions/almenon.arepl-1.0.13/out/src/extension
[2019-04-12 20:58:29.129] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-server-ready {"startup":false,"activationEvent":"onDebugResolve"}
[2019-04-12 20:58:29.129] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-server-ready/dist/extension
[2019-04-12 21:00:17.655] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:17.658] [exthost] [error] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
	at normalizeSpawnArguments (child_process.js:412:11)
	at Object.spawn (child_process.js:534:38)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38123)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:18.178] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:18.179] [exthost] [error] TypeError: Cannot read property 'on' of undefined
	at d (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38176)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38328)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:19.796] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:19.797] [exthost] [error] TypeError: Cannot read property 'on' of undefined
	at d (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38176)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38328)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:20.459] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:20.459] [exthost] [error] TypeError: Cannot read property 'on' of undefined
	at d (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38176)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38328)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:20.962] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:20.962] [exthost] [error] TypeError: Cannot read property 'on' of undefined
	at d (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38176)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38328)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:21.755] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:21.755] [exthost] [error] TypeError: Cannot read property 'on' of undefined
	at d (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38176)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38328)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:00:28.823] [exthost] [error] [ms-python.python] provider FAILED
[2019-04-12 21:00:28.823] [exthost] [error] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
	at normalizeSpawnArguments (child_process.js:412:11)
	at Object.spawn (child_process.js:534:38)
	at module.exports.t.ProcessService.exec (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:9:38123)
	at h.<anonymous> (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:631913)
	at Generator.next (<anonymous>)
	at s (/home/andre/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:630756)
[2019-04-12 21:02:04.906] [exthost] [error] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at PythonShell.send (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/node_modules/python-shell/index.js:269:20)
	at PythonEvaluator.execCode (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/node_modules/arepl-backend/index.js:58:22)
	at ToAREPLLogic.onUserInput (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/out/src/toAREPLLogic.js:44:34)
	at PreviewManager.onAnyDocChange (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/out/src/PreviewManager.js:199:31)
	at PreviewManager.runArepl (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/out/src/PreviewManager.js:59:14)
	at vscode.commands.registerCommand (/home/andre/.vscode/extensions/almenon.arepl-1.0.13/out/src/extension.js:24:24)
	at d._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:160)
	at d.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:534)
	at h._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:593:118)
	at h._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:777)
	at h._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:436)
	at h._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:565)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:39:64)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at s (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) extension.executeAREPL
```

**Comment by Almenon** [comment]
You're correct, that is caused by arepl using python 2. You can either download the python extension and point that to python 3 (arepl will use setting from python extension if it is there) or directly change the arepl.pythonPath setting

**Comment by Almenon** [comment]
let me know if you run into any problems or need any other help :)
