### ISSUE TITLE
Issue with Anaconda/numpy

### ISSUE THREAD

**Issue by kuelshammer** [Almenon/AREPL-vscode#241]
> Things like operating system, python version (python --version from terminal) are helpful.
Win10 x64
conda --version:
conda 4.6.11
python --version:
Python 3.7.3

If you want to be REALLY helpful you can run the VSCode command "Developer: Open Log File...", choose Extension Host, and copy the file here. Posting the python code you put in arepl could also be helpful.

Output in AREPL window:
Traceback (most recent call last):
  File "c:\Users\Max\.vscode\extensions\almenon.arepl-1.0.13\node_modules\arepl-backend\python\pythonEvaluator.py", line 105, in <module>
    import jsonpickle.ext.numpy as jsonpickle_numpy
  File "c:\Users\Max\.vscode\extensions\almenon.arepl-1.0.13\node_modules\arepl-backend\python\jsonpickle\ext\numpy.py", line 8, in <module>
    import numpy as np
  File "C:\tools\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\tools\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Logfile:
[2019-04-16 16:00:53.697] [exthost] [info] extension host started
[2019-04-16 16:00:53.730] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-04-16 16:00:53.730] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\python\out\pythonMain
[2019-04-16 16:00:53.733] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-04-16 16:00:53.733] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\ms-python.python-2019.3.6558\out\client\extension
[2019-04-16 16:00:53.871] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode {"startup":false,"activationEvent":"onLanguage:python"}
[2019-04-16 16:00:53.871] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.5\dist\intellicode
[2019-04-16 16:00:53.966] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:53.966] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
[2019-04-16 16:00:53.971] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:53.971] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
[2019-04-16 16:00:53.976] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:53.976] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main
[2019-04-16 16:00:54.012] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.012] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
[2019-04-16 16:00:54.023] [exthost] [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.023] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\christian-kohler.path-intellisense-1.4.2\out\src\extension
[2019-04-16 16:00:54.048] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-close-tag {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.048] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\formulahendry.auto-close-tag-0.5.6\out\src\extension
[2019-04-16 16:00:54.051] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-rename-tag {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.051] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\formulahendry.auto-rename-tag-0.0.15\out\src\extension
[2019-04-16 16:00:54.056] [exthost] [info] ExtensionService#_doActivateExtension HookyQR.beautify {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.056] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\hookyqr.beautify-1.4.11\extension
[2019-04-16 16:00:54.137] [exthost] [info] ExtensionService#_doActivateExtension pranaygp.vscode-css-peek {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.137] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\pranaygp.vscode-css-peek-2.2.0\out\client\src\extension
[2019-04-16 16:00:54.210] [exthost] [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons {"startup":true,"activationEvent":"*"}
[2019-04-16 16:00:54.210] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\Max\.vscode\extensions\vscode-icons-team.vscode-icons-8.5.0\out\src\
[2019-04-16 16:00:58.811] [exthost] [info] eager extensions activated
[2019-04-16 16:01:32.054] [exthost] [info] ExtensionService#_doActivateExtension almenon.arepl {"startup":false,"activationEvent":"onCommand:extension.newAREPLSession"}
[2019-04-16 16:01:32.054] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\Max\.vscode\extensions\almenon.arepl-1.0.13\out\src\extension

**Comment by Almenon** [comment]
Thanks for reporting this issue.  If you look in the vscode settings what are the values of python.pythonPath, python.condaPath, and arepl.pythonPath?

**Comment by Almenon** [comment]
Also I'm guessing the issue is due to https://github.com/Almenon/AREPL-vscode/issues/243 - I'm not activating conda before using it.

**Comment by ZainlessBrombie** [comment]
The needed dlls for numpy are in the conda environment, which by default is not in the PATH variable. As a workaround:
https://stackoverflow.com/questions/36778066/importerror-dll-load-failed-when-importing-numpy-installed-in-conda-virtual-env refers to two directories which contain/should contain dlls. Add these to Your %PATH% and try again.

**Comment by Almenon** [comment]
I finally got around to downloading miniconda and I was able to reproduce this issue. It happens on startup if you have numpy installed in conda.

> Error in the AREPL extension!
AREPL crashed unexpectedly! Are you using python 3? err: 1

```
Print Output:
Traceback (most recent call last):
  File "C:\Users\caleb\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\pythonEvaluator.py", line 102, in <module>
    import jsonpickle.ext.numpy as jsonpickle_numpy
  File "C:\Users\caleb\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\jsonpickle\ext\numpy.py", line 8, in <module>
    import numpy as np
  File "C:\Users\caleb\Miniconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\caleb\Miniconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

```

**Comment by Almenon** [comment]
This bug will be partially fixed with https://github.com/Almenon/AREPL-backend/issues/93 - importing numpy will still fail, but at least it will not cause arepl to completely crash. (other imports will still work)

**Comment by kuelshammer** [comment]
Thanks for your work. As I liked AREPLs approach so much I deinstalled Anaconda and use a pure Python setup.

**Comment by Almenon** [comment]
I've finally released a new version of arepl with  Almenon/AREPL-backend#93 fix -  importing numpy will still fail, but at least it will not cause arepl to completely crash at startup. (arepl in a conda env will work as long as you don't try importing numpy).
