### ISSUE TITLE
TypeError Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#251]
```
TypeError: Cannot read property 'setEncoding' of undefined 	at /Users/anon/.vscode/extensions/almenon.arepl-1.0.14/node_modules/python-shell/index.js:99:39 	at Array.forEach (<anonymous>) 	at new PythonShell (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/node_modules/python-shell/index.js:97:39) 	at PythonEvaluator.startPython (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/node_modules/arepl-backend/index.js:111:24) 	at PreviewManager.startAndBindPython (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/PreviewManager.js:153:34) 	at PreviewManager.<anonymous> (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/PreviewManager.js:52:18) 	at Generator.next (<anonymous>) 	at __awaiter (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/PreviewManager.js:7:71) 	at new Promise (<anonymous>) 	at __awaiter (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/PreviewManager.js:3:12) 	at PreviewManager.startArepl (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/PreviewManager.js:40:16) 	at vscode.commands.registerCommand (/Users/anon/.vscode/extensions/almenon.arepl-1.0.14/out/src/extension.js:12:24) 	at d._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:477:621) 	at d.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:478:6) 	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11) 	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716) 	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:394) 	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141) 	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400) 	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708) 	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460) 	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708) 	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467) 	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513) 	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708) 	at y._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276) 	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415) 	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708) 	at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35) 	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410) 	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689) 	at Socket.emit (events.js:182:13) 	at addChunk (_stream_readable.js:279:12) 	at readableAddChunk (_stream_readable.js:264:11) 	at Socket.Readable.push (_stream_readable.js:219:10) 	at Pipe.onread (net.js:636:20)
```

If you run into this issue please let me know what python path you have configured.

**Comment by Almenon** [comment]
I've only seen this happen on Darwin 18.2.0 OS so far

**Comment by rhotog** [comment]
I am getting this error too.  Fresh install of Anaconda and VS Code on a mac.  Installed the AREPL extension and I get the following error in a new document window:

`Error in the AREPL extension!
Error running python with command: /Users/anon/anaconda3 -u
TypeError: Cannot read property 'setEncoding' of undefined
	at /Users/anon/.vscode/extensions/almenon.arepl-1.0.16/node_modules/python-shell/index.js:99:39
	at Array.forEach (<anonymous>)
	at new PythonShell (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/node_modules/python-shell/index.js:97:39)
	at python_evaluator.start (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/node_modules/arepl-backend/index.js:112:24)
	at PreviewManager.startAndBindPython (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/PreviewManager.js:146:35)
	at PreviewManager.<anonymous> (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/PreviewManager.js:54:18)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/PreviewManager.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/PreviewManager.js:3:12)
	at PreviewManager.startArepl (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/PreviewManager.js:40:16)
	at vscode.commands.registerCommand.vscodeUtilities_1.default.newUnsavedPythonDoc.then (/Users/anon/.vscode/extensions/almenon.arepl-1.0.16/out/src/extension.js:17:42)

Print Output:
`

**Comment by Almenon** [comment]
Thanks for giving me the python path - For some reason one of 'stdout', 'stdin', 'stderr' is null after spawning the process and I'm not sure why. I just have a windows laptop at the moment but once I get back home I'll be able to test python paths on my ubuntu VM. In the meantime I would suggest using python3 instead of anaconda for AREPL if possible. AREPL doesn't support anaconda very well because the anaconda environment needs to be activated to work properly.

**Comment by rhotog** [comment]
Thanks, I’ll give it a try!

**Comment by Almenon** [comment]
note to self: https://github.com/extrabacon/python-shell/pull/191 might change the error. Maybe even fix it, but I doubt it.
