### ISSUE TITLE
AREPL doesn't work out-of-the-box in WSL with python ext installed in windows but not in WSL

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#293]
For some reason the vscode settings api returns the python path in windows even if you are in WSL. The windows path might not work in WSL. I've asked slack if there is a solution, hopefully someone will respond. The workaround is to specify arepl python path or to download python ext in wsl.

**Comment by Almenon** [comment]
I checked slack and I didn't see where I asked that :| The search function didn't return anything either. Weird.

I ran into this issue again but was not able to reproduce it
```
Error in the AREPL extension!
Error running python with command: python -u /home/almenon/.vscode-server/extensions/almenon.arepl-2.0.1/node_modules/arepl-backend/python/arepl_python_evaluator.py
Error: spawn python ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/
```
