### ISSUE TITLE
AREPL isn't evaluating anything/no errors either

### ISSUE THREAD

**Issue by SanjayS5** [Almenon/AREPL-vscode#311]
After installing AREPL and choosing to evaluate current python file, I type code in and the AREPL UI doesn't do anything other than display the default "Start typing or make a change and your code will be evaluated." screen. 

Any ideas?

**Comment by Almenon** [comment]
If you go to the top menu and click on "help" then "toggle developer tools" are there any error messages displayed in the console when you open AREPL?

**Comment by Almenon** [comment]
Also what value do you have for `arepl.pythonpath` and `python.pythonpath`?

**Comment by SanjayS5** [comment]
Oh boy. It's literally pages long. I'm not sure how much of it you need, but I'll paste the section furthest down. Also I'm guessing those values would be set in the settings.json yeah?

So it's "python.pythonPath": "${workspaceFolder}/venv/bin/python" 

and I don't have arepl.pythonpath anywhere in that file. 

`
mainThreadExtensionService.ts:44 TypeError: util_1.promisify is not a function
	at Function.getVersion (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/node_modules/python-shell/index.js:240:36)
	at PreviewManager.startAndBindPython (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:134:36)
	at PreviewManager.<anonymous> (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:54:18)
	at Generator.next (<anonymous>)
	at /Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:3:12)
	at PreviewManager.startArepl (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:40:16)
	at vscode.commands.registerCommand (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/extension.js:13:24)
	at e._executeContributedCommand (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:675:6)
	at e._doInvokeHandler (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:832)
	at e._invokeHandler (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:550)
	at e._receiveRequest (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:631)
	at e._receiveOneMessage (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:400)
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
	at e.fire (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
	at Socket.<anonymous> (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:43 [almenon.arepl]Cannot read property 'pyshell' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 TypeError: Cannot read property 'pyshell' of undefined
	at PreviewManager.dispose (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:116:34)
	at PreviewManager.panel.onDidDispose (/Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18/out/src/PreviewManager.js:52:43)
	at e.fire (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:784)
	at e.dispose (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:730:990)
	at e.$onDidDisposeWebviewPanel (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:733:870)
	at e._doInvokeHandler (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:832)
	at e._invokeHandler (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:550)
	at e._receiveRequest (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:631)
	at e._receiveOneMessage (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:400)
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
	at /private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
	at e.fire (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
	at Socket.<anonymous> (/private/var/folders/tv/hyf8m3qj48l4mbn30x_6g1yr0000gn/T/AppTranslocation/11559C88-C27E-43CD-A9C7-1D8CF2814C78/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560`

**Comment by Almenon** [comment]
You're on an old version of Arepl. Can you try uninstalling and reinstalling arepl please?

In the logs you posted:
> almenon.arepl-1.0.18

Current version is 1.0.21

**Comment by SanjayS5** [comment]
Just tried that. The version is 1.0.21 before hitting install but after installing it's 1.0.18

**Comment by Almenon** [comment]
Vscode keeps the old version of the extension sometimes. Try uninstalling, deleting Users/sanjay/.vscode/extensions/almenon.arepl-1.0.18, then reinstalling and you should have the right version

**Comment by SanjayS5** [comment]
Okay did that as well. It's still installing an older version than what's being stated on vscode

**Comment by SanjayS5** [comment]
Found the issue. My VS Code version was 1.21.1 instead of the latest which at the time of writing is 1.43.0. Reinstalling the latest version solved the issue. Thanks for the effort in helping me figure this out :) AREPL works great!

**Comment by Almenon** [comment]
That makes sense. Good problem solving!
