### ISSUE TITLE
internal arepl error

### ISSUE THREAD

**Issue by bjh-developer** [Almenon/AREPL-vscode#315]
**Describe the bug**
When I start to use AREPL, this error came out when I was coding:

internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at PythonShell.send (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\node_modules\python-shell\index.js:285:20)
	at PythonEvaluator.execCode (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\node_modules\arepl-backend\index.js:62:22)
	at ToAREPLLogic.onUserInput (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\out\src\toAREPLLogic.js:79:34)
	at PreviewManager.onAnyDocChange (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\out\src\PreviewManager.js:270:51)
	at listOnTimeout (internal/timers.js:533:17)
	at processTimers (internal/timers.js:475:7)

**To Reproduce**
1. Click on the AREPL icon on the top right corner
2. Start coding

**Expected behavior**
I expected it to be able to work

**Comment by Almenon** [comment]
See #309 

What do you have for python.pythonpath and arepl.pythonpath settings? If you try changing arepl.pythonpath or python.pythonpath you could probably get arepl to work.

**Comment by bjh-developer** [comment]
My settings for python.pythonpath are 'python' for both user and workspace.
while my settings for arepl.pythonpath are blank for both user and workspace.

What should i change?

Thanks for the fast comment

**Comment by Almenon** [comment]
I'm guessing that when you invoke python in the command line it opens up the Microsoft store to install python. You can either install python that way or you can add your existing python installation to your PATH so windows can find it.

**Comment by Almenon** [comment]
Did you fix it?

**Comment by bjh-developer** [comment]
Actually I have not managed to fix it but is ok, maybe there's a problem at my side as I am using a school laptop. There are restrictions.

**Comment by bjh-developer** [comment]
Don't worry, I have managed to get it working. :)
