### ISSUE TITLE
Temporary Bug Fix

### ISSUE THREAD

**Issue by exgin** [Almenon/AREPL-vscode#331]
So I've recently got this error using AREPL
```
internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at PythonShell.send (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\python-shell\index.js:285:20)
	at PythonEvaluator.execCode (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\index.js:62:22)
	at ToAREPLLogic.onUserInput (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.23\out\src\toAREPLLogic.js:79:34)
	at PreviewManager.onAnyDocChange (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.23\out\src\PreviewManager.js:271:51)
	at listOnTimeout (internal/timers.js:533:17)
	at processTimers (internal/timers.js:475:7)
````

![err4](https://user-images.githubusercontent.com/59214236/81109275-d88e1080-8ee7-11ea-8668-92762fa34862.PNG)

And I noticed, when I have a .vscode folder in my code base with settings.json:
```
{
  "python.pythonPath": "venv\\Scripts\\python.exe"
}
```
The error goes away & I can see my variables and everything on AREPL
Is there anyway to have this has a default path in AREPL so I don't have to or vscode doesn't have to keep creating that folder?

**Comment by Almenon** [comment]
> Is there anyway to have this has a default path in AREPL so I don't have to or vscode doesn't have to keep creating that folder?

Assuming you are not in a vscode workspace, the python extension needs to save the settings to `.vscode/settings.json` so it can know what python interpreter you are using in the folder. Otherwise when you closed the folder and reopened it again the python extension wouldn't know what interpreter to use. But if you don't like that for some reason I suppose you could set `arepl.pythonpath` directly in your settings.

Hopefully that helps :)

Are you able to execute python in the command line? If so what is the output of `which python`?

**Comment by exgin** [comment]
Setting arepl.pyhtonpath worked out thanks

**Comment by Julian3012** [comment]
I also get this error, but I have set arepl.pythonpath on my workspace and my user settings.

I am working with macos.

![image](https://user-images.githubusercontent.com/12408751/116892657-55a1b200-ac30-11eb-9178-e795a46c6c83.png)

![image](https://user-images.githubusercontent.com/12408751/116892723-6a7e4580-ac30-11eb-983c-521db08fbb5f.png)

**Comment by aploos29** [comment]
![Screenshot 2021-07-11 063055](https://user-images.githubusercontent.com/74877387/125181856-99f19580-e211-11eb-8e1b-d4a2816a527d.png)

What is wrong with AREPL running and how can I fix it?
