### ISSUE TITLE
error when opening file descriptor directly

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#335]
**Describe the bug**
In arepl v1.0.23 it runs into a error on the very first line:
```
hi
Traceback (most recent call last):
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 275, in <module>
    main(input())
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 266, in main
    print_output(return_info)
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 239, in print_output
    print("6q3co7" + json.dumps(output, default=lambda x: x.__dict__))
OSError: [Errno 9] Bad file descriptor
```

In the beta version of arepl I'm testing it gets the following error:
```
Traceback (most recent call last):
  line 2, in <module>
OSError: [WinError 6] The handle is invalid
```

**To Reproduce**
```python
print('hi', file=open(1,'w'))
print('hi', file=open(1,'w'))
```

**Expected behavior**
The following print results are outputted:
```
hi
hi
```

**Screenshots**

**Other Information (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.1

**Additional context**
The workaround is using `sys.stdout` instead of `open(1,'w')`

**Comment by Almenon** [comment]
I'm pretty sure this is a backend-related error - I opened https://github.com/Almenon/AREPL-backend/issues/125

**Comment by Almenon** [comment]
If you run into this problem please comment to let me know.
