### ISSUE TITLE
Not able to invoke REPL

### ISSUE THREAD

**Issue by gighead** [Almenon/AREPL-vscode#353]
**Describe the bug**
Not able to use AREPL 

**To Reproduce**
1. Go to 'AREPL icon 

```internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at PythonShell.send (/Users/anon/.vscode/extensions/almenon.arepl-1.0.24/node_modules/python-shell/index.js:282:20)
	at PythonEvaluator.execCode (/Users/anon/.vscode/extensions/almenon.arepl-1.0.24/node_modules/arepl-backend/index.js:71:22)
	at ToAREPLLogic.onUserInput (/Users/anon/.vscode/extensions/almenon.arepl-1.0.24/out/src/toAREPLLogic.js:79:34)
	at PreviewManager.onAnyDocChange (/Users/anon/.vscode/extensions/almenon.arepl-1.0.24/out/src/PreviewManager.js:273:51)
	at Timeout._onTimeout (/Users/anon/.vscode/extensions/ms-azuretools.vscode-azureterraform-0.3.1/node_modules/async-listener/glue.js:188:31)
	at listOnTimeout (internal/timers.js:533:17)
	at processTimers (internal/timers.js:475:7)

Print Output:
  File "/Users/uname/.vscode/extensions/almenon.arepl-1.0.24/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 44
    userError: str,
             ^
SyntaxError: invalid syntax
Variables:
```

report an issue | ⭐ rate me ⭐ | talk on gitter | Tweet #arepl
**Expected behavior**

**Screenshots**

**Other Information (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. 22]

**Additional context**

**Comment by Almenon** [comment]
What are the values of arepl.pythonpath and python.pythonpath? AREPL only works with python 3.5 or greater.

**Comment by Almenon** [comment]
`SyntaxError: invalid syntax` indicates AREPL is being ran with python 2, which is not supported.

**Comment by Almenon** [comment]
No response - closing
