### ISSUE TITLE
Error with numpy

### ISSUE THREAD

**Issue by csarami** [Almenon/AREPL-vscode#386]
I am using VS code with Python 3.7.6 64-bit. The code below run in termial fine ( prints the array) however, it returns error below using AREPL.

```
import numpy as np
a = [[1,4,7],[2,9,7],[1,3,0],[9,6,9]]
b = [[2,3,4],[2,2,2], [1,1,1],[0,0,0]]
A = np.array([a,b])
print(A)
```

Here is the error:
`Traceback (most recent call last):
  line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/overrides.py", line 46, in <module>
    """)
RuntimeError: implement_array_function method already has a docstring

Print Output:
Variables:
{}`

**Comment by Almenon** [comment]
Your code snippet worked for me on windows 10 with both python 3.7 and python 3.6. What version of numpy are you using?

**Comment by F0ax** [comment]
Same issue over here.
Python 3.8
Win10

`Traceback (most recent call last):
  line 2, in <module>
  File "C:\Users\A104354918\AppData\Local\WPy64-3800\python-3.8.0.amd64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\A104354918\AppData\Local\WPy64-3800\python-3.8.0.amd64\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\A104354918\AppData\Local\WPy64-3800\python-3.8.0.amd64\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\A104354918\AppData\Local\WPy64-3800\python-3.8.0.amd64\lib\site-packages\numpy\core\overrides.py", line 16, in <module>
    add_docstring(
RuntimeError: implement_array_function method already has a docstring`

**Comment by Almenon** [comment]
weird. I run into the same error. Not sure why it happens, but you can fix it by upgrading numpy to version 1.19
