### ISSUE TITLE
internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by BeastDog** [Almenon/AREPL-vscode#389]
Hey, just installed the extension and i get this error:

internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:399:19)
	at writeOrBuffer (_stream_writable.js:387:5)
	at Socket.Writable.write (_stream_writable.js:318:11)
	at PythonShell.send (c:\Users\anon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\python-shell\index.js:319:20)
	at PythonEvaluator.execCode (c:\Users\anon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\index.js:71:22)
	at ToAREPLLogic.onUserInput (c:\Users\anon\.vscode\extensions\almenon.arepl-2.0.2\out\src\toAREPLLogic.js:80:34)
	at PreviewManager.onAnyDocChange (c:\Users\anon\.vscode\extensions\almenon.arepl-2.0.2\out\src\PreviewManager.js:278:51)
	at listOnTimeout (internal/timers.js:551:17)
	at processTimers (internal/timers.js:492:7)

**Comment by Almenon** [comment]
What python version and OS are you using? Where do you see the error?

**Comment by BeastDog** [comment]
i use 3.9.4. on windows 10.
i see the error here : https://gyazo.com/a22a4f83d629b4064d5384ab0476d6d9

**Comment by Almenon** [comment]
Thanks, and does this always happen when you open arepl?

**Comment by BeastDog** [comment]
yes.

**Comment by Almenon** [comment]
In your settings what's the value of `python.pythonpath`?

**Comment by BeastDog** [comment]
where can i see it?

**Comment by Almenon** [comment]
In VSCode press control-comma. This opens up then settings pane. In the settings pane search for `python.pythonpath`

**Comment by BeastDog** [comment]
C:\Users\Nir Kremer\AppData\Local\Programs\Python\Python39

**Comment by Almenon** [comment]
Okay, so you're definitely using python 3.9 🤔 However I'm also using 3.9 and I'm not getting the same error. Are you free to hop on a zoom meeting by any chance?

**Comment by BeastDog** [comment]
tbh i dont have zoom, do you have discord?

**Comment by Almenon** [comment]
yep! almenon#9385

**Comment by Almenon** [comment]
I was able to reproduce the error - the python path is invalid (doesn't point directly to executable) but AREPL shows stream destroyed error instead of saying that the python path is bad. I need to fix it so it says that your python path is bad.

**Comment by Almenon** [comment]
The fix for this has been released w/ version 2.0.3. Thanks again for the bug report!
