### ISSUE TITLE
SystemError: Parent module 'asyncio' not loaded, cannot perform relative impor

### ISSUE THREAD

**Issue by KikeVen** [Almenon/AREPL-vscode#418]
I had imported asyncio, got the following error. Removed the import and all the associated asyncio and still getting the following error.

```cmp
Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "c:\Users\k\.vscode-insiders\extensions\almenon.arepl-2.0.3\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 298, in main
    return_info = exec_input(execArgs)
  File "c:\Users\k\.vscode-insiders\extensions\almenon.arepl-2.0.3\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 234, in exec_input
    asyncio.set_event_loop(asyncio.new_event_loop())
  File "C:\Users\k\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 642, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "C:\Users\k\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 617, in get_event_loop_policy
    _init_event_loop_policy()
  File "C:\Users\k\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 610, in _init_event_loop_policy
    from . import DefaultEventLoopPolicy
SystemError: Parent module 'asyncio' not loaded, cannot perform relative import
```

**Comment by Almenon** [comment]
You're on python 3.5. AREPL requires python 3.7 or greater. What version of AREPL are you on?

**Comment by KikeVen** [comment]
I am using 3.7.4 64-bit venv. This environment is part of a workspace in vscode

**Comment by Almenon** [comment]
Arepl v2.0.3 has an update that should automatically use the python path you have chosen with the python extension. Are you using arepl v2.0.3 and the python extension?

**Comment by KikeVen** [comment]
Yes, I am running v2.0.3. As I mentioned before, mine is part of a
Workspace, vscode asks which venv I want to use, the problem might be
there. Not VSCode, but AREPL should be aware of it. Again when I open the
project as a stand alone it works only when I open the project as part of a
Workspace I get the posted error.

**Comment by Almenon** [comment]
Can you send me a full-screen screenshot of VSCode when the error appears please?

**Comment by KikeVen** [comment]
Sure, emailed.

Thank you

**Comment by Almenon** [comment]
KikeVen emailed me, this definitely looks like a bug. Possibly a bug with the python extension - it may be giving me the wrong path, because he has python 3.7 yet AREPL is running python 3.5

**Comment by Almenon** [comment]
What version of the python extension are you on?

**Comment by Almenon** [comment]
Nevermind, confirmed this is a issue with the latest python version. I was able to reproduce the scenario and get the wrong version of python in AREPL.

**Comment by KikeVen** [comment]
Sorry for the tardiness, didn't have access to my system until now. I am running vscode - insider version 1.59.0 and AREPL for Python version 2.0.3

**Comment by hotenov** [comment]
Today I ran into a similar problem with importing modules and wrong detection of Python interpreter for AREPL extension. I use `poetry`, by the way. I think, this is due to Python extension changed setting name to `python.defaultInterpreterPath` (instead of old `python.pythonPath`).

Default value is `python` and it's not changed after selecting Python interpreter (stay `python' in settings but changed in the bottom of VS Code (status bar) . I had to set path explicitly in settings:
![image](https://user-images.githubusercontent.com/11818507/129472237-3f8ba105-a8f2-4695-b68f-4f244ad0c4e3.png)

Python path for AREPL extension stays blank (by default)

This helped me.  
But **pay attention**: if you use multi-folder workspace, path to folder must be absolute path (not relative).  
Or use absolute path to Python interpreter in settings (but don't forget that other workspace's folders will be take this path, that's why I uses place holder `${workspaceFolder}`.

I work on Windows, therefore `\` in paths.
