### ISSUE TITLE
multiple traceback not being modified correctly 

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#70]
Code:
```python
import requests
```
Error:
```python
Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    from . import urllib3
  File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 41, in <module>
    from .request import RequestMethods
  File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\request.py", line 7, in <module>
    from .filepost import encode_multipart_formdata
  File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\filepost.py", line 9, in <module>
    from .fields import RequestField
ImportError: No module named 'requests.packages.urllib3.fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  line 1, in <module>
  File "C:\Python\Python35\lib\site-packages\requests\__init__.py", line 64, in <module>
    from . import utils
  File "C:\Python\Python35\lib\site-packages\requests\utils.py", line 24, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Python\Python35\lib\site-packages\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "C:\Python\Python35\lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named 'urllib3'
```

The second traceback is missing the part where it shows the code in line 1:
>     import requests

**Comment by Almenon** [comment]
I forgot that I had hid that on purpose.... akward

The reasoning being that showing the code was unnecessary when you could see the code on the left given the line number.  Which sort of makes sense?  Except because my first instinct was to report it as a bug maybe it wasn't such a good idea.  I'll leave it be unless I get complaints about it.
